"""multi-tenancy: tenant users, system access, tenant databases, demo/prod instances

Revision ID: 26ceb51d07e7
Revises: 442942c97667
Create Date: 2026-09-28 20:11:26.734409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ceb51d07e7'
down_revision = '442942c97667'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='access_environment'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED', name='system_access_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('storage_limit_mb', sa.Integer(), nullable=True),
    sa.Column('request_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'system_id', 'environment', name='uq_system_access_tenant_system_env')
    )
    op.create_index(op.f('ix_system_access_system_id'), 'system_access', ['system_id'], unique=False)
    op.create_index(op.f('ix_system_access_tenant_id'), 'system_access', ['tenant_id'], unique=False)
    op.create_table('tenant_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='tenant_db_environment'), nullable=False),
    sa.Column('database_identifier', sa.String(length=63), nullable=False),
    sa.Column('database_host_ref', sa.String(length=80), nullable=False),
    sa.Column('database_name', sa.String(length=63), nullable=False),
    sa.Column('database_user_ref', sa.String(length=63), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PROVISIONING', 'READY', 'FAILED', 'DEPROVISIONING', 'DEPROVISIONED', name='tenant_db_status'), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_identifier'),
    sa.UniqueConstraint('tenant_id', 'system_id', 'environment', name='uq_tenant_db_tenant_system_env')
    )
    op.create_index(op.f('ix_tenant_databases_system_id'), 'tenant_databases', ['system_id'], unique=False)
    op.create_index(op.f('ix_tenant_databases_tenant_id'), 'tenant_databases', ['tenant_id'], unique=False)
    op.create_table('demo_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('system_access_id', sa.UUID(), nullable=False),
    sa.Column('tenant_database_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'PROVISIONING', 'READY', 'FAILED', 'DEPROVISIONING', 'DEPROVISIONED', name='demo_instance_status'), nullable=False),
    sa.Column('reset_policy', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_access_id'], ['system_access.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_database_id'], ['tenant_databases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_access_id')
    )
    op.create_index(op.f('ix_demo_instances_tenant_id'), 'demo_instances', ['tenant_id'], unique=False)
    op.create_table('production_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('system_access_id', sa.UUID(), nullable=False),
    sa.Column('tenant_database_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'PROVISIONING', 'READY', 'FAILED', 'DEPROVISIONING', 'DEPROVISIONED', name='production_instance_status'), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_access_id'], ['system_access.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_database_id'], ['tenant_databases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_access_id')
    )
    op.create_index(op.f('ix_production_instances_tenant_id'), 'production_instances', ['tenant_id'], unique=False)
    op.create_table('tenant_database_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_database_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_database_id'], ['tenant_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_database_id')
    )
    op.create_table('tenant_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT_ADMIN', 'CLIENT_USER', name='tenant_member_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', 'REMOVED', name='tenant_member_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_users_tenant_user')
    )
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_users_user_id'), 'tenant_users', ['user_id'], unique=False)
    # Alembic no emite el CREATE TYPE automaticamente cuando un Enum se usa
    # por primera vez via add_column (si no, solo en create_table).
    sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenant_status').create(op.get_bind(), checkfirst=True)
    op.add_column('tenants', sa.Column('display_name', sa.String(length=120), nullable=False, server_default=''))
    op.add_column('tenants', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenant_status'), nullable=False, server_default='ACTIVE'))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('tenants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'display_name')
    op.drop_index(op.f('ix_tenant_users_user_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_table('tenant_database_credentials')
    op.drop_index(op.f('ix_production_instances_tenant_id'), table_name='production_instances')
    op.drop_table('production_instances')
    op.drop_index(op.f('ix_demo_instances_tenant_id'), table_name='demo_instances')
    op.drop_table('demo_instances')
    op.drop_index(op.f('ix_tenant_databases_tenant_id'), table_name='tenant_databases')
    op.drop_index(op.f('ix_tenant_databases_system_id'), table_name='tenant_databases')
    op.drop_table('tenant_databases')
    op.drop_index(op.f('ix_system_access_tenant_id'), table_name='system_access')
    op.drop_index(op.f('ix_system_access_system_id'), table_name='system_access')
    op.drop_table('system_access')
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in (
        "access_environment",
        "system_access_status",
        "tenant_db_environment",
        "tenant_db_status",
        "demo_instance_status",
        "production_instance_status",
        "tenant_member_role",
        "tenant_member_status",
        "tenant_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
