"""add tenant_hostnames table

Revision ID: 3edabb706dee
Revises: 7ccb8f57afad
Create Date: 2026-10-08 02:17:12.255534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edabb706dee'
down_revision = '7ccb8f57afad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_hostnames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='tenant_hostname_environment'), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', name='uq_tenant_hostnames_hostname')
    )
    op.create_index(op.f('ix_tenant_hostnames_system_id'), 'tenant_hostnames', ['system_id'], unique=False)
    op.create_index(op.f('ix_tenant_hostnames_tenant_id'), 'tenant_hostnames', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_hostnames_tenant_id'), table_name='tenant_hostnames')
    op.drop_index(op.f('ix_tenant_hostnames_system_id'), table_name='tenant_hostnames')
    op.drop_table('tenant_hostnames')
    # ### end Alembic commands ###
    sa.Enum(name="tenant_hostname_environment").drop(op.get_bind(), checkfirst=True)
