"""mfa and staged sessions

Revision ID: 41d7413fc3a8
Revises: a448b4209cd2
Create Date: 2026-10-08 10:57:18.461331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d7413fc3a8'
down_revision = 'a448b4209cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('stage', sa.String(length=20), server_default='FULL', nullable=False))
    op.add_column('user_sessions', sa.Column('mfa_failed_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('mfa_last_step', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'mfa_totp_secret',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Los secretos cifrados no entran en VARCHAR(64): se desactiva MFA antes.
    op.execute("UPDATE users SET mfa_totp_secret = NULL, mfa_enabled = false")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mfa_totp_secret',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'mfa_last_step')
    op.drop_column('user_sessions', 'mfa_failed_attempts')
    op.drop_column('user_sessions', 'stage')
    # ### end Alembic commands ###
