"""add systems catalog

Revision ID: 442942c97667
Revises: f71eaa5e03a7
Create Date: 2026-09-28 19:49:49.023449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442942c97667'
down_revision = 'f71eaa5e03a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_description', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('demo_available', sa.Boolean(), nullable=False),
    sa.Column('production_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systems')
    # ### end Alembic commands ###
