"""demo request privacy and ip

Revision ID: 491afbcedc36
Revises: 6089547cc3fe
Create Date: 2026-10-08 11:31:20.063405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '491afbcedc36'
down_revision = '6089547cc3fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_requests', sa.Column('privacy_version', sa.String(length=40), nullable=True))
    op.add_column('demo_requests', sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('demo_requests', sa.Column('client_ip', postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_requests', 'client_ip')
    op.drop_column('demo_requests', 'privacy_accepted_at')
    op.drop_column('demo_requests', 'privacy_version')
    # ### end Alembic commands ###
