"""demo email notices

Revision ID: 6089547cc3fe
Revises: 41d7413fc3a8
Create Date: 2026-10-08 11:13:26.548739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6089547cc3fe'
down_revision = '41d7413fc3a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_instances', sa.Column('reminder_3d_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('demo_instances', sa.Column('reminder_1d_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('demo_instances', sa.Column('expired_notice_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_instances', 'expired_notice_sent_at')
    op.drop_column('demo_instances', 'reminder_1d_sent_at')
    op.drop_column('demo_instances', 'reminder_3d_sent_at')
    # ### end Alembic commands ###
