"""control center: product template fields, tenant contact, instance config, service registry, demo requests, jobs

Revision ID: 7ccb8f57afad
Revises: ee6aa1d8e4f6
Create Date: 2026-09-29 02:11:19.280618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ccb8f57afad'
down_revision = 'ee6aa1d8e4f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL_SERVICE', 'EXTERNAL_SERVICE', 'MANAGED_PRODUCT', name='registry_service_type'), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='registry_environment'), nullable=True),
    sa.Column('public_hostname', sa.String(length=255), nullable=True),
    sa.Column('internal_target', sa.String(length=255), nullable=False),
    sa.Column('healthcheck_path', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', 'UNKNOWN', name='registry_health_status'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('system_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'APPROVED', 'REJECTED', 'PROVISIONED', name='demo_request_status'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instance_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='instance_config_environment'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'system_id', 'environment', 'version', name='uq_instance_config_version')
    )
    op.create_index(op.f('ix_instance_configurations_tenant_id'), 'instance_configurations', ['tenant_id'], unique=False)
    op.create_table('instance_secret_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='instance_secret_environment'), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'system_id', 'environment', 'key', name='uq_instance_secret_key')
    )
    op.create_index(op.f('ix_instance_secret_values_tenant_id'), 'instance_secret_values', ['tenant_id'], unique=False)
    op.create_table('provisioning_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEMO_PROVISION', 'PRODUCTION_PROVISION', 'DEMO_TO_PRODUCTION', name='job_type'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('DEMO', 'PRODUCTION', name='job_environment'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status'), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_jobs_tenant_id'), 'provisioning_jobs', ['tenant_id'], unique=False)
    op.add_column('systems', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.false()))
    sa.Enum('PENDING', 'PARTIAL', 'READY', name='system_implementation_status').create(op.get_bind(), checkfirst=True)
    op.add_column('systems', sa.Column(
        'implementation_status',
        sa.Enum('PENDING', 'PARTIAL', 'READY', name='system_implementation_status'),
        nullable=False, server_default='PENDING',
    ))
    op.add_column('systems', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('systems', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('systems', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('systems', sa.Column('default_demo_duration_days', sa.Integer(), nullable=False, server_default='14'))
    op.add_column('systems', sa.Column('default_max_users', sa.Integer(), nullable=True))
    op.add_column('systems', sa.Column('default_storage_mb', sa.Integer(), nullable=True))
    op.add_column('systems', sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('systems', sa.Column('modules_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('systems', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tenants', sa.Column('ruc', sa.String(length=30), nullable=True))
    op.add_column('tenants', sa.Column('primary_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('tenants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('contact_name', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'contact_name')
    op.drop_column('tenants', 'city')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'primary_email')
    op.drop_column('tenants', 'ruc')
    op.drop_column('systems', 'updated_at')
    op.drop_column('systems', 'modules_schema')
    op.drop_column('systems', 'config_schema')
    op.drop_column('systems', 'default_storage_mb')
    op.drop_column('systems', 'default_max_users')
    op.drop_column('systems', 'default_demo_duration_days')
    op.drop_column('systems', 'video_url')
    op.drop_column('systems', 'image_url')
    op.drop_column('systems', 'icon')
    op.drop_column('systems', 'implementation_status')
    op.drop_column('systems', 'is_public')
    op.drop_index(op.f('ix_provisioning_jobs_tenant_id'), table_name='provisioning_jobs')
    op.drop_table('provisioning_jobs')
    op.drop_index(op.f('ix_instance_secret_values_tenant_id'), table_name='instance_secret_values')
    op.drop_table('instance_secret_values')
    op.drop_index(op.f('ix_instance_configurations_tenant_id'), table_name='instance_configurations')
    op.drop_table('instance_configurations')
    op.drop_table('demo_requests')
    op.drop_table('service_registry')
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in (
        "registry_service_type", "registry_environment", "registry_health_status",
        "demo_request_status", "instance_config_environment", "instance_secret_environment",
        "job_type", "job_environment", "job_status", "system_implementation_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
