"""sales credit notes and returns

Revision ID: 0b4e58d9d0a6
Revises: 5e234767cef5
Create Date: 2026-10-08 11:19:38.686279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0b4e58d9d0a6'
down_revision = '5e234767cef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_credit_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('RETURN', 'DISCOUNT', name='credit_note_kind'), nullable=False),
    sa.Column('fiscal_status', postgresql.ENUM('INTERNAL_SIMULATION', 'PENDING_TRANSMISSION', 'APPROVED', 'REJECTED', 'CANCELLED', name='fiscal_status', create_type=False), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('restocked', sa.Boolean(), nullable=False),
    sa.Column('taxable_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exempt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fiscal_status = 'INTERNAL_SIMULATION'", name='ck_sales_credit_notes_fiscal_gate'),
    sa.CheckConstraint('applied_amount >= 0 AND applied_amount <= total', name='ck_sales_credit_notes_applied_range'),
    sa.CheckConstraint('taxable_10 + vat_10 + taxable_5 + vat_5 + exempt = total', name='ck_sales_credit_notes_breakdown_sums'),
    sa.CheckConstraint('total > 0', name='ck_sales_credit_notes_total_positive'),
    sa.CheckConstraint('unapplied_amount >= 0 AND applied_amount + unapplied_amount = total', name='ck_sales_credit_notes_amounts_consistent'),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_sales_credit_notes_customer_id'), 'sales_credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_credit_notes_invoice_id'), 'sales_credit_notes', ['invoice_id'], unique=False)
    op.create_table('sales_credit_note_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_note_id', sa.UUID(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('order_line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('line_total > 0 AND line_total = line_net + line_tax', name='ck_sales_credit_note_lines_amounts'),
    sa.CheckConstraint('quantity >= 0', name='ck_sales_credit_note_lines_quantity_non_negative'),
    sa.ForeignKeyConstraint(['credit_note_id'], ['sales_credit_notes.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['sales_order_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_credit_note_lines_credit_note_id'), 'sales_credit_note_lines', ['credit_note_id'], unique=False)
    op.add_column('sales_order_lines', sa.Column('quantity_returned', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False))
    op.add_column('sales_order_lines', sa.Column('amount_credited', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    # Autogenerate no detecta CHECK nuevos en tablas existentes: a mano.
    op.create_check_constraint("ck_sales_order_lines_returned_range", "sales_order_lines",
                               "quantity_returned >= 0 AND quantity_returned <= quantity")
    op.create_check_constraint("ck_sales_order_lines_credited_range", "sales_order_lines",
                               "amount_credited >= 0 AND amount_credited <= line_total")
    # ### end Alembic commands ###

    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [{"code": "CREDIT_NOTE", "prefix": "NC-", "next_value": 1}])


def downgrade() -> None:
    op.execute("DELETE FROM document_sequences WHERE code = 'CREDIT_NOTE'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_sales_order_lines_credited_range", "sales_order_lines", type_="check")
    op.drop_constraint("ck_sales_order_lines_returned_range", "sales_order_lines", type_="check")
    op.drop_column('sales_order_lines', 'amount_credited')
    op.drop_column('sales_order_lines', 'quantity_returned')
    op.drop_index(op.f('ix_sales_credit_note_lines_credit_note_id'), table_name='sales_credit_note_lines')
    op.drop_table('sales_credit_note_lines')
    op.drop_index(op.f('ix_sales_credit_notes_invoice_id'), table_name='sales_credit_notes')
    op.drop_index(op.f('ix_sales_credit_notes_customer_id'), table_name='sales_credit_notes')
    op.drop_table('sales_credit_notes')
    # ### end Alembic commands ###
    sa.Enum(name="credit_note_kind").drop(op.get_bind(), checkfirst=True)
