"""inventory movements and balances

Revision ID: 13e7ce183686
Revises: 43663f4ef304
Create Date: 2026-10-08 04:03:39.113294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e7ce183686'
down_revision = '43663f4ef304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_balances',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand >= 0', name='ck_stock_balances_on_hand_non_negative'),
    sa.CheckConstraint('reserved <= on_hand', name='ck_stock_balances_reserved_le_on_hand'),
    sa.CheckConstraint('reserved >= 0', name='ck_stock_balances_reserved_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'warehouse_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'ISSUE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'TRANSFER_IN', 'TRANSFER_OUT', 'REVERSAL', name='stock_movement_type'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('reverses_movement_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('direction IN (1, -1)', name='ck_stock_movements_direction'),
    sa.CheckConstraint('quantity > 0', name='ck_stock_movements_quantity_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_stock_movements_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reverses_movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reverses_movement_id')
    )
    op.create_index(op.f('ix_stock_movements_group_id'), 'stock_movements', ['group_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_idempotency_key'), 'stock_movements', ['idempotency_key'], unique=False)
    op.create_index('ix_stock_movements_product_created', 'stock_movements', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###

    # El libro de movimientos es inmutable A NIVEL BASE: un error se corrige
    # con un movimiento de reversion, nunca editando o borrando historia.
    op.execute("""
        CREATE FUNCTION forbid_stock_movement_changes() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'stock_movements es inmutable: usar un movimiento de reversion'
                USING ERRCODE = 'restrict_violation';
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER trg_stock_movements_immutable
        BEFORE UPDATE OR DELETE ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION forbid_stock_movement_changes();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_stock_movements_immutable ON stock_movements")
    op.execute("DROP FUNCTION IF EXISTS forbid_stock_movement_changes()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_created', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_idempotency_key'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_group_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_balances')
    # ### end Alembic commands ###
    sa.Enum(name="stock_movement_type").drop(op.get_bind(), checkfirst=True)
