"""erp core masters

Revision ID: 43663f4ef304
Revises: 
Create Date: 2026-10-08 03:50:45.639581

"""
import datetime
import uuid
from decimal import Decimal

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43663f4ef304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('establishment_code', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('ruc_dv', sa.String(length=1), nullable=True),
    sa.Column('ruc_status', sa.Enum('UNVERIFIED', 'FORMAT_OK', 'VERIFIED_PROVIDER', 'FICTITIOUS', name='ruc_verification_status'), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_limit >= 0', name='ck_parties_credit_limit_non_negative'),
    sa.CheckConstraint('is_customer OR is_supplier', name='ck_parties_has_role'),
    sa.CheckConstraint('payment_terms_days >= 0', name='ck_parties_payment_terms_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc', name='uq_parties_ruc')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('taxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name='ck_taxes_rate_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'valid_from', name='uq_taxes_code_valid_from')
    )
    op.create_table('units_of_measure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('ruc_dv', sa.String(length=1), nullable=True),
    sa.Column('ruc_is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_company_single_row'),
    sa.ForeignKeyConstraint(['base_currency'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.Enum('GOOD', 'SERVICE', name='product_type'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tracks_stock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_cost >= 0', name='ck_products_average_cost_non_negative'),
    sa.CheckConstraint('sale_price >= 0', name='ck_products_sale_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_warehouses_branch_id'), 'warehouses', ['branch_id'], unique=False)
    # ### end Alembic commands ###

    # Datos de referencia minimos. Las tasas de IVA son DATOS versionados
    # (valid_from), no constantes en codigo: 10% general, 5% reducida y
    # exenta segun la ley vigente al momento de esta carga -- revisar con
    # contador antes de produccion. valid_from=1900-01-01 marca "carga
    # inicial", no una fecha legal.
    currencies = sa.table("currencies", sa.column("code"), sa.column("name"), sa.column("decimals"), sa.column("is_active"))
    op.bulk_insert(currencies, [
        {"code": "PYG", "name": "Guarani", "decimals": 0, "is_active": True},
        {"code": "USD", "name": "Dolar estadounidense", "decimals": 2, "is_active": True},
    ])
    units = sa.table("units_of_measure", sa.column("id", sa.UUID()), sa.column("code"), sa.column("name"))
    op.bulk_insert(units, [
        {"id": uuid.uuid4(), "code": "UN", "name": "Unidad"},
        {"id": uuid.uuid4(), "code": "KG", "name": "Kilogramo"},
        {"id": uuid.uuid4(), "code": "LT", "name": "Litro"},
        {"id": uuid.uuid4(), "code": "MT", "name": "Metro"},
        {"id": uuid.uuid4(), "code": "HR", "name": "Hora"},
        {"id": uuid.uuid4(), "code": "SRV", "name": "Servicio"},
    ])
    taxes = sa.table("taxes", sa.column("id", sa.UUID()), sa.column("code"), sa.column("name"), sa.column("rate"), sa.column("valid_from"))
    initial = datetime.date(1900, 1, 1)
    op.bulk_insert(taxes, [
        {"id": uuid.uuid4(), "code": "IVA10", "name": "IVA 10%", "rate": Decimal("10.00"), "valid_from": initial},
        {"id": uuid.uuid4(), "code": "IVA5", "name": "IVA 5%", "rate": Decimal("5.00"), "valid_from": initial},
        {"id": uuid.uuid4(), "code": "EXENTA", "name": "Exenta", "rate": Decimal("0.00"), "valid_from": initial},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_branch_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('company')
    op.drop_table('units_of_measure')
    op.drop_table('taxes')
    op.drop_table('product_categories')
    op.drop_table('parties')
    op.drop_table('currencies')
    op.drop_table('branches')
    # ### end Alembic commands ###
    sa.Enum(name="ruc_verification_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="product_type").drop(op.get_bind(), checkfirst=True)
