"""accounting general ledger

Revision ID: 5e234767cef5
Revises: 8cb0b22fdea3
Create Date: 2026-10-08 04:21:59.932404

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e234767cef5'
down_revision = '8cb0b22fdea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='account_type'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_postable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fiscal_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='period_status'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_fiscal_periods_month_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_fiscal_periods_year_month')
    )
    op.create_table('account_mappings',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('reverses_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('reverses_entry_id')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index('ix_journal_entries_source', 'journal_entries', ['source_type', 'source_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.CheckConstraint('(debit > 0) <> (credit > 0)', name='ck_journal_lines_one_side'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_journal_lines_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'line_no', name='uq_journal_lines_entry_line')
    )
    op.create_index('ix_journal_lines_account', 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_entry_id'), 'journal_lines', ['entry_id'], unique=False)
    # ### end Alembic commands ###

    # --- Plan de cuentas inicial (GENERICO, de gestion). Requiere revision de
    # un contador antes de produccion; cada empresa puede ajustarlo.
    chart = [
        # code, name, type, parent, postable
        ("1", "Activo", "ASSET", None, False),
        ("1.1", "Activo corriente", "ASSET", "1", False),
        ("1.1.01", "Caja", "ASSET", "1.1", True),
        ("1.1.02", "Bancos", "ASSET", "1.1", True),
        ("1.1.03", "Deudores por ventas", "ASSET", "1.1", True),
        ("1.1.04", "Anticipos a proveedores", "ASSET", "1.1", True),
        ("1.1.05", "IVA credito fiscal", "ASSET", "1.1", True),
        ("1.1.06", "Mercaderias", "ASSET", "1.1", True),
        ("2", "Pasivo", "LIABILITY", None, False),
        ("2.1", "Pasivo corriente", "LIABILITY", "2", False),
        ("2.1.01", "Proveedores", "LIABILITY", "2.1", True),
        ("2.1.02", "Anticipos de clientes", "LIABILITY", "2.1", True),
        ("2.1.03", "IVA debito fiscal 10%", "LIABILITY", "2.1", True),
        ("2.1.04", "IVA debito fiscal 5%", "LIABILITY", "2.1", True),
        ("2.1.05", "Mercaderias recibidas a facturar", "LIABILITY", "2.1", True),
        ("3", "Patrimonio neto", "EQUITY", None, False),
        ("3.1.01", "Capital", "EQUITY", "3", True),
        ("3.2.01", "Resultados acumulados", "EQUITY", "3", True),
        ("4", "Ingresos", "INCOME", None, False),
        ("4.1.01", "Ventas de mercaderias y servicios", "INCOME", "4", True),
        ("5", "Costos", "EXPENSE", None, False),
        ("5.1.01", "Costo de mercaderias vendidas", "EXPENSE", "5", True),
        ("6", "Gastos", "EXPENSE", None, False),
        ("6.1.01", "Gastos generales", "EXPENSE", "6", True),
        ("6.1.02", "Diferencias de inventario", "EXPENSE", "6", True),
    ]
    ids = {code: uuid.uuid4() for code, *_ in chart}
    accounts = sa.table("accounts", sa.column("id", sa.UUID()), sa.column("code"), sa.column("name"),
                        sa.column("account_type"), sa.column("parent_id", sa.UUID()), sa.column("is_postable"),
                        sa.column("is_active"))
    op.bulk_insert(accounts, [
        {"id": ids[c], "code": c, "name": n, "account_type": t, "parent_id": ids[par] if par else None,
         "is_postable": post, "is_active": True}
        for c, n, t, par, post in chart
    ])
    mappings = {
        "CASH": "1.1.01", "BANK": "1.1.02", "AR": "1.1.03", "SUPPLIER_ADVANCES": "1.1.04", "VAT_INPUT": "1.1.05",
        "INVENTORY": "1.1.06", "AP": "2.1.01", "CUSTOMER_ADVANCES": "2.1.02", "VAT_OUTPUT_10": "2.1.03",
        "VAT_OUTPUT_5": "2.1.04", "GRNI": "2.1.05", "RETAINED_EARNINGS": "3.2.01", "SALES_REVENUE": "4.1.01",
        "COGS": "5.1.01", "EXPENSE_DEFAULT": "6.1.01", "INVENTORY_ADJUSTMENT": "6.1.02",
    }
    mtable = sa.table("account_mappings", sa.column("key"), sa.column("account_id", sa.UUID()))
    op.bulk_insert(mtable, [{"key": k, "account_id": ids[c]} for k, c in mappings.items()])

    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [{"code": "JOURNAL_ENTRY", "prefix": "AS-", "next_value": 1}])

    # --- Garantias en la base ------------------------------------------------
    # 1) Partida doble: al COMMIT, cada asiento tocado tiene >= 2 lineas y
    #    suma debe = haber. Diferido para poder insertar las lineas de a una.
    op.execute("""
        CREATE FUNCTION check_journal_entry_balanced() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE d NUMERIC; c NUMERIC; n INTEGER;
        BEGIN
            SELECT coalesce(sum(debit), 0), coalesce(sum(credit), 0), count(*)
              INTO d, c, n FROM journal_lines WHERE entry_id = NEW.entry_id;
            IF n < 2 OR d <> c THEN
                RAISE EXCEPTION 'Asiento % desbalanceado (debe %, haber %, lineas %)', NEW.entry_id, d, c, n
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NULL;
        END $$;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_journal_lines_balanced
        AFTER INSERT ON journal_lines DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION check_journal_entry_balanced();
    """)
    # 2) Inmutabilidad: asientos y lineas no se editan ni se borran.
    op.execute("""
        CREATE FUNCTION forbid_journal_changes() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'La contabilidad es inmutable: usar un asiento de reversion'
                USING ERRCODE = 'restrict_violation';
        END $$;
    """)
    op.execute("CREATE TRIGGER trg_journal_entries_immutable BEFORE UPDATE OR DELETE ON journal_entries "
               "FOR EACH ROW EXECUTE FUNCTION forbid_journal_changes();")
    op.execute("CREATE TRIGGER trg_journal_lines_immutable BEFORE UPDATE OR DELETE ON journal_lines "
               "FOR EACH ROW EXECUTE FUNCTION forbid_journal_changes();")


def downgrade() -> None:
    for trg, tbl in (("trg_journal_lines_immutable", "journal_lines"), ("trg_journal_entries_immutable", "journal_entries"),
                     ("trg_journal_lines_balanced", "journal_lines")):
        op.execute(f"DROP TRIGGER IF EXISTS {trg} ON {tbl}")
    op.execute("DROP FUNCTION IF EXISTS forbid_journal_changes()")
    op.execute("DROP FUNCTION IF EXISTS check_journal_entry_balanced()")
    op.execute("DELETE FROM document_sequences WHERE code = 'JOURNAL_ENTRY'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_lines_entry_id'), table_name='journal_lines')
    op.drop_index('ix_journal_lines_account', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index('ix_journal_entries_source', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('account_mappings')
    op.drop_table('fiscal_periods')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    for name in ("account_type", "period_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
