"""purchases and payables

Revision ID: 8cb0b22fdea3
Revises: d654ac7086bf
Create Date: 2026-10-08 04:16:59.697228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cb0b22fdea3'
down_revision = 'd654ac7086bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', postgresql.ENUM('CASH', 'TRANSFER', 'CARD', 'CHECK', 'OTHER', name='payment_method', create_type=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('POSTED', 'VOIDED', name='receipt_status', create_type=False), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payments_amount_positive'),
    sa.CheckConstraint('unapplied_amount >= 0 AND unapplied_amount <= amount', name='ck_supplier_payments_unapplied_range'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index('uq_supplier_payments_idempotency', 'supplier_payments', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('subtotal_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total >= 0', name='ck_purchase_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('line_total = line_net + line_tax', name='ck_purchase_order_lines_total_consistent'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_order_lines_quantity_positive'),
    sa.CheckConstraint('quantity_received >= 0 AND quantity_received <= quantity', name='ck_purchase_order_lines_received_range'),
    sa.CheckConstraint('unit_price >= 0', name='ck_purchase_order_lines_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_no', name='uq_purchase_order_lines_order_line')
    )
    op.create_index(op.f('ix_purchase_order_lines_order_id'), 'purchase_order_lines', ['order_id'], unique=False)
    op.create_table('supplier_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_timbrado', sa.String(length=20), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('ISSUED', 'VOIDED', name='invoice_status', create_type=False), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('taxable_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exempt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance_due >= 0 AND balance_due <= total', name='ck_supplier_invoices_balance_range'),
    sa.CheckConstraint('due_date >= issue_date', name='ck_supplier_invoices_due_after_issue'),
    sa.CheckConstraint('taxable_10 + vat_10 + taxable_5 + vat_5 + exempt = total', name='ck_supplier_invoices_breakdown_sums'),
    sa.CheckConstraint('total > 0', name='ck_supplier_invoices_total_positive'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoices_purchase_order_id'), 'supplier_invoices', ['purchase_order_id'], unique=False)
    op.create_index('ix_supplier_invoices_supplier_due', 'supplier_invoices', ['supplier_id', 'due_date'], unique=False)
    op.create_index('uq_supplier_invoices_number', 'supplier_invoices', ['supplier_id', 'supplier_invoice_number'], unique=True, postgresql_where=sa.text("status = 'ISSUED'"))
    op.create_table('supplier_payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['supplier_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payment_allocations_invoice_id'), 'supplier_payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_payment_id'), 'supplier_payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###

    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [
        {"code": "PURCHASE_ORDER", "prefix": "OC-", "next_value": 1},
        {"code": "SUPPLIER_PAYMENT", "prefix": "PP-", "next_value": 1},
    ])


def downgrade() -> None:
    op.execute("DELETE FROM document_sequences WHERE code IN ('PURCHASE_ORDER', 'SUPPLIER_PAYMENT')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payment_allocations_payment_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_invoice_id'), table_name='supplier_payment_allocations')
    op.drop_table('supplier_payment_allocations')
    op.drop_index('uq_supplier_invoices_number', table_name='supplier_invoices', postgresql_where=sa.text("status = 'ISSUED'"))
    op.drop_index('ix_supplier_invoices_supplier_due', table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_purchase_order_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_index(op.f('ix_purchase_order_lines_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('uq_supplier_payments_idempotency', table_name='supplier_payments', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
    sa.Enum(name="purchase_order_status").drop(op.get_bind(), checkfirst=True)
