"""sales orders and document sequences

Revision ID: aee18fddad86
Revises: 13e7ce183686
Create Date: 2026-10-08 04:07:58.314554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee18fddad86'
down_revision = '13e7ce183686'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'DELIVERED', 'CANCELLED', name='sales_order_status'), nullable=False),
    sa.Column('payment_condition', sa.Enum('CASH', 'CREDIT', name='payment_condition'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total >= 0 AND subtotal_net >= 0 AND tax_total >= 0', name='ck_sales_orders_amounts'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_sales_orders_customer_id'), 'sales_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.CheckConstraint('discount_pct >= 0 AND discount_pct <= 100', name='ck_sales_order_lines_discount_range'),
    sa.CheckConstraint('line_total = line_net + line_tax', name='ck_sales_order_lines_total_consistent'),
    sa.CheckConstraint('quantity > 0', name='ck_sales_order_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_lines_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_no', name='uq_sales_order_lines_order_line')
    )
    op.create_index(op.f('ix_sales_order_lines_order_id'), 'sales_order_lines', ['order_id'], unique=False)
    # ### end Alembic commands ###

    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [{"code": "SALES_ORDER", "prefix": "OV-", "next_value": 1}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_lines_order_id'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_customer_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
    sa.Enum(name="sales_order_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_condition").drop(op.get_bind(), checkfirst=True)
