"""hr payroll attendance

Revision ID: afd02f3c9860
Revises: 7c1e5a92d3f4
Create Date: 2026-10-08 23:26:25.873383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afd02f3c9860'
down_revision = '7c1e5a92d3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=True),
    sa.Column('reason', sa.String(length=250), nullable=False),
    sa.Column('included_on', sa.Date(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_blocklist_national_id'), 'hr_blocklist', ['national_id'], unique=False)
    op.create_table('hr_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('default_trade', sa.String(length=100), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('manual_rate', sa.Boolean(), nullable=False),
    sa.CheckConstraint('hourly_rate >= 0', name='ck_hr_categories_rate'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('hr_settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('pay_period', sa.Enum('BIWEEKLY', 'MONTHLY', name='hr_pay_period'), nullable=False),
    sa.Column('workday_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rounding_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('attendance_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('deduct_ips', sa.Boolean(), nullable=False),
    sa.Column('ips_employee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ips_employer_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_hr_settings_singleton'),
    sa.CheckConstraint('ips_employee_pct >= 0 AND ips_employee_pct <= 100 AND ips_employer_pct >= 0 AND ips_employer_pct <= 100', name='ck_hr_settings_ips_pct'),
    sa.CheckConstraint('overtime_multiplier >= 1', name='ck_hr_settings_ot_mult'),
    sa.CheckConstraint('rounding_minutes IN (1, 5, 10, 15, 30)', name='ck_hr_settings_rounding'),
    sa.CheckConstraint('workday_hours > 0 AND workday_hours <= 24', name='ck_hr_settings_workday'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('workdays', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('tolerance_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geofence_radius_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name='ck_hr_sites_geo_pair'),
    sa.CheckConstraint('geofence_radius_m BETWEEN 20 AND 5000', name='ck_hr_sites_radius'),
    sa.CheckConstraint('tolerance_minutes >= 0 AND tolerance_minutes <= 120', name='ck_hr_sites_tolerance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('hr_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('bound_fingerprint', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('hr_employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('last_names', sa.String(length=120), nullable=False),
    sa.Column('first_names', sa.String(length=120), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('pay_method', sa.Enum('CASH', 'TRANSFER', name='hr_pay_method'), nullable=False),
    sa.Column('bank_account', sa.String(length=60), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus_per_hour', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ips_entry', sa.Date(), nullable=True),
    sa.Column('ips_exit', sa.Date(), nullable=True),
    sa.Column('ips_notes', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('family_notes', sa.Text(), nullable=True),
    sa.Column('training', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('references_notes', sa.Text(), nullable=True),
    sa.Column('custom_start', sa.Time(), nullable=True),
    sa.Column('custom_end', sa.Time(), nullable=True),
    sa.Column('tracks_attendance', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(custom_start IS NULL) = (custom_end IS NULL)', name='ck_hr_employees_custom_pair'),
    sa.CheckConstraint('hourly_rate >= 0 AND bonus_per_hour >= 0', name='ck_hr_employees_rates'),
    sa.CheckConstraint('ips_exit IS NULL OR ips_entry IS NULL OR ips_exit >= ips_entry', name='ck_hr_employees_ips_range'),
    sa.ForeignKeyConstraint(['category_id'], ['hr_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id', name='uq_hr_employees_ci')
    )
    op.create_table('hr_payrolls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CLOSED', name='hr_payroll_status'), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_ips_employee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_ips_employer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_advances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'CLOSED') = (closed_at IS NOT NULL)", name='ck_hr_payrolls_closed_at'),
    sa.CheckConstraint('period_end >= period_start', name='ck_hr_payrolls_range'),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('hr_site_day_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_hr_site_day_range'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_hr_site_day_weekday'),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'weekday', name='uq_hr_site_day')
    )
    op.create_table('hr_absences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('VACATION', 'PERMISSION', 'MEDICAL', 'OTHER', name='hr_absence_kind'), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_hr_absences_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_absences_employee_id'), 'hr_absences', ['employee_id'], unique=False)
    op.create_table('hr_advances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pay_method', sa.Enum('CASH', 'TRANSFER', name='hr_pay_method'), nullable=False),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sa.String(length=250), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_hr_advances_amount'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_hr_advances_advance_date'), 'hr_advances', ['advance_date'], unique=False)
    op.create_index(op.f('ix_hr_advances_employee_id'), 'hr_advances', ['employee_id'], unique=False)
    op.create_table('hr_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_hr_assignments_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_assignments_employee_id'), 'hr_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_assignments_site_id'), 'hr_assignments', ['site_id'], unique=False)
    op.create_index('uq_hr_assignments_open', 'hr_assignments', ['employee_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('hr_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=True),
    sa.Column('time_out', sa.Time(), nullable=True),
    sa.Column('regular_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='hr_overtime_status'), nullable=False),
    sa.Column('paid_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'DEVICE', 'IMPORT', name='hr_attendance_source'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('in_client_id', sa.String(length=80), nullable=True),
    sa.Column('out_client_id', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(overtime_hours = 0) = (overtime_status = 'NONE')", name='ck_hr_attendance_ot_status'),
    sa.CheckConstraint('regular_hours >= 0 AND overtime_hours >= 0 AND paid_hours >= 0', name='ck_hr_attendance_hours'),
    sa.ForeignKeyConstraint(['device_id'], ['hr_devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'site_id', 'work_date', name='uq_hr_attendance_day')
    )
    op.create_index(op.f('ix_hr_attendance_employee_id'), 'hr_attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_hr_attendance_site_id'), 'hr_attendance', ['site_id'], unique=False)
    op.create_index(op.f('ix_hr_attendance_work_date'), 'hr_attendance', ['work_date'], unique=False)
    op.create_table('hr_manual_overtime',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours > 0 AND hours <= 24', name='ck_hr_manual_overtime_hours'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['hr_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_manual_overtime_employee_id'), 'hr_manual_overtime', ['employee_id'], unique=False)
    op.create_table('hr_payroll_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(length=250), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('pay_method', sa.Enum('CASH', 'TRANSFER', name='hr_pay_method'), nullable=False),
    sa.Column('bank_account', sa.String(length=60), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('unexcused_absences', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ips_employee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ips_employer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('advances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('bonus_forced', sa.Boolean(), nullable=False),
    sa.Column('adjustment_note', sa.String(length=250), nullable=True),
    sa.CheckConstraint('gross = base_amount + overtime_amount + bonus_amount + adjustment', name='ck_hr_payroll_lines_gross'),
    sa.CheckConstraint('net = gross - ips_employee - advances', name='ck_hr_payroll_lines_net'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['hr_payrolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_id', 'employee_id', name='uq_hr_payroll_lines_employee')
    )
    op.create_table('hr_payroll_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('force_bonus', sa.Boolean(), nullable=False),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=250), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('adjustment = 0 OR reason IS NOT NULL', name='ck_hr_payroll_overrides_reason'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_start', 'period_end', name='uq_hr_payroll_overrides_period')
    )
    # ### end Alembic commands ###

    # Configuracion por defecto (legal Paraguay: jornada 8 h, extra +50 %,
    # IPS 9 % obrero / 16,5 % patronal) y numeracion.
    op.execute("INSERT INTO hr_settings (id, pay_period, workday_hours, rounding_minutes, overtime_multiplier, "
               "attendance_bonus_enabled, deduct_ips, ips_employee_pct, ips_employer_pct) "
               "VALUES (1, 'BIWEEKLY', 8, 15, 1.5, false, true, 9, 16.5)")
    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [{"code": "HR_ADVANCE", "prefix": "AD-", "next_value": 1},
                          {"code": "HR_PAYROLL", "prefix": "PL-", "next_value": 1}])
    # Una planilla CLOSED y sus lineas son el respaldo de lo que se pago: no
    # se modifican ni se borran (correccion = ajuste en el periodo siguiente).
    op.execute("""
        CREATE FUNCTION hr_payroll_closed_guard() RETURNS trigger AS $$
        DECLARE st text;
        BEGIN
            IF TG_TABLE_NAME = 'hr_payrolls' THEN
                IF OLD.status = 'CLOSED' THEN
                    RAISE EXCEPTION 'planilla % cerrada: no se modifica', OLD.number;
                END IF;
            ELSE
                SELECT status INTO st FROM hr_payrolls WHERE id = OLD.payroll_id;
                IF st = 'CLOSED' THEN
                    RAISE EXCEPTION 'linea de planilla cerrada: no se modifica';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        CREATE TRIGGER trg_hr_payrolls_closed BEFORE UPDATE OR DELETE ON hr_payrolls
            FOR EACH ROW EXECUTE FUNCTION hr_payroll_closed_guard();
        CREATE TRIGGER trg_hr_payroll_lines_closed BEFORE UPDATE OR DELETE ON hr_payroll_lines
            FOR EACH ROW EXECUTE FUNCTION hr_payroll_closed_guard();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_hr_payroll_lines_closed ON hr_payroll_lines")
    op.execute("DROP TRIGGER IF EXISTS trg_hr_payrolls_closed ON hr_payrolls")
    op.execute("DROP FUNCTION IF EXISTS hr_payroll_closed_guard()")
    op.execute("DELETE FROM document_sequences WHERE code IN ('HR_ADVANCE', 'HR_PAYROLL')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_payroll_overrides')
    op.drop_table('hr_payroll_lines')
    op.drop_index(op.f('ix_hr_manual_overtime_employee_id'), table_name='hr_manual_overtime')
    op.drop_table('hr_manual_overtime')
    op.drop_index(op.f('ix_hr_attendance_work_date'), table_name='hr_attendance')
    op.drop_index(op.f('ix_hr_attendance_site_id'), table_name='hr_attendance')
    op.drop_index(op.f('ix_hr_attendance_employee_id'), table_name='hr_attendance')
    op.drop_table('hr_attendance')
    op.drop_index('uq_hr_assignments_open', table_name='hr_assignments', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_index(op.f('ix_hr_assignments_site_id'), table_name='hr_assignments')
    op.drop_index(op.f('ix_hr_assignments_employee_id'), table_name='hr_assignments')
    op.drop_table('hr_assignments')
    op.drop_index(op.f('ix_hr_advances_employee_id'), table_name='hr_advances')
    op.drop_index(op.f('ix_hr_advances_advance_date'), table_name='hr_advances')
    op.drop_table('hr_advances')
    op.drop_index(op.f('ix_hr_absences_employee_id'), table_name='hr_absences')
    op.drop_table('hr_absences')
    op.drop_table('hr_site_day_schedules')
    op.drop_table('hr_payrolls')
    op.drop_table('hr_employees')
    op.drop_table('hr_devices')
    op.drop_table('hr_sites')
    op.drop_table('hr_settings')
    op.drop_table('hr_categories')
    op.drop_index(op.f('ix_hr_blocklist_national_id'), table_name='hr_blocklist')
    op.drop_table('hr_blocklist')
    # ### end Alembic commands ###
    for t in ("hr_pay_period", "hr_pay_method", "hr_overtime_status", "hr_attendance_source", "hr_absence_kind",
              "hr_payroll_status"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
