"""invoices receipts receivables

Revision ID: d654ac7086bf
Revises: aee18fddad86
Create Date: 2026-10-08 04:12:01.505184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd654ac7086bf'
down_revision = 'aee18fddad86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'TRANSFER', 'CARD', 'CHECK', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'VOIDED', name='receipt_status'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_customer_receipts_amount_positive'),
    sa.CheckConstraint('unapplied_amount >= 0 AND unapplied_amount <= amount', name='ck_customer_receipts_unapplied_range'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_customer_receipts_customer_id'), 'customer_receipts', ['customer_id'], unique=False)
    op.create_index('uq_customer_receipts_idempotency', 'customer_receipts', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('sales_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'VOIDED', name='invoice_status'), nullable=False),
    sa.Column('fiscal_status', sa.Enum('INTERNAL_SIMULATION', 'PENDING_TRANSMISSION', 'APPROVED', 'REJECTED', 'CANCELLED', name='fiscal_status'), nullable=False),
    sa.Column('payment_condition', postgresql.ENUM('CASH', 'CREDIT', name='payment_condition', create_type=False), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('taxable_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_10', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_5', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exempt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('balance_due >= 0 AND balance_due <= total', name='ck_sales_invoices_balance_range'),
    sa.CheckConstraint('due_date >= issue_date', name='ck_sales_invoices_due_after_issue'),
    sa.CheckConstraint('taxable_10 + vat_10 + taxable_5 + vat_5 + exempt = total', name='ck_sales_invoices_breakdown_sums'),
    sa.CheckConstraint('total >= 0', name='ck_sales_invoices_total_non_negative'),
    sa.ForeignKeyConstraint(['currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_sales_invoices_customer_due', 'sales_invoices', ['customer_id', 'due_date'], unique=False)
    op.create_index('uq_sales_invoices_active_order', 'sales_invoices', ['order_id'], unique=True, postgresql_where=sa.text("status = 'ISSUED'"))
    op.create_table('receipt_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_receipt_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['customer_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_allocations_invoice_id'), 'receipt_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_receipt_allocations_receipt_id'), 'receipt_allocations', ['receipt_id'], unique=False)
    # ### end Alembic commands ###

    # GATE TRIBUTARIO en la base: mientras no exista integracion SIFEN
    # validada y habilitada, ningun comprobante puede dejar de ser simulacion.
    # Levantar esto requiere una migracion explicita (ver docs/ERP_DATA_MODEL.md).
    op.create_check_constraint(
        "ck_sales_invoices_fiscal_gate", "sales_invoices", "fiscal_status = 'INTERNAL_SIMULATION'"
    )

    seqs = sa.table("document_sequences", sa.column("code"), sa.column("prefix"), sa.column("next_value"))
    op.bulk_insert(seqs, [
        {"code": "INVOICE_INTERNAL", "prefix": "FI-", "next_value": 1},
        {"code": "CUSTOMER_RECEIPT", "prefix": "RC-", "next_value": 1},
    ])


def downgrade() -> None:
    op.execute("DELETE FROM document_sequences WHERE code IN ('INVOICE_INTERNAL', 'CUSTOMER_RECEIPT')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_allocations_receipt_id'), table_name='receipt_allocations')
    op.drop_index(op.f('ix_receipt_allocations_invoice_id'), table_name='receipt_allocations')
    op.drop_table('receipt_allocations')
    op.drop_index('uq_sales_invoices_active_order', table_name='sales_invoices', postgresql_where=sa.text("status = 'ISSUED'"))
    op.drop_index('ix_sales_invoices_customer_due', table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index('uq_customer_receipts_idempotency', table_name='customer_receipts', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_customer_receipts_customer_id'), table_name='customer_receipts')
    op.drop_table('customer_receipts')
    # ### end Alembic commands ###
    for name in ("payment_method", "receipt_status", "invoice_status", "fiscal_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
